"""
TODO: Create Jinja2 templates for dynamic configuration generation

Your mission:
1. Create templates directory structure
2. Build base configuration template
3. Create specialized templates for VLANs and interfaces
4. Test template rendering with your variables
"""

# Basic configuration template to create:
base_template = '''
{# TODO: Create this as templates/base_config.j2 #}
!
! Base Configuration Template
! Generated by Ansible - {{ ansible_date_time.date }}
! Device: {{ inventory_hostname }}
!
hostname {{ hostname }}
!
ip domain-name {{ domain_name }}
!
{# NTP Configuration from group_vars #}
{% for ntp_server in ntp_servers %}
ntp server {{ ntp_server }}
{% endfor %}
!
{# Interface Configuration - only if interfaces are defined #}
{% if interfaces is defined %}
{% for interface in interfaces %}
!
interface {{ interface.name }}
 description {{ interface.description | default("Managed by Ansible") }}
{% if interface.ip is defined %}
 ip address {{ interface.ip }} {{ interface.mask }}
{% endif %}
 no shutdown
{% endfor %}
{% endif %}
!
{# Router-specific configuration #}
{% if routing_protocol is defined %}
router {{ routing_protocol }} {{ ospf_process_id | default(1) }}
 network 0.0.0.0 255.255.255.255 area {{ ospf_area | default(0) }}
{% endif %}
!
end
'''

# VLAN template for switches:
vlan_template = '''
{# TODO: Create this as templates/vlan_config.j2 #}
!
! VLAN Configuration Template  
! Device: {{ inventory_hostname }}
!
{% for vlan in vlans %}
vlan {{ vlan.id }}
 name {{ vlan.name | upper }}
{% endfor %}
!
{# VLAN Interfaces if defined #}
{% if vlan_interfaces is defined %}
{% for vlan_int in vlan_interfaces %}
!
interface vlan{{ vlan_int.vlan_id }}
 description {{ vlan_int.description }}
 ip address {{ vlan_int.ip }} {{ vlan_int.mask }}
 no shutdown
{% endfor %}
{% endif %}
!
'''

# Test playbook template:
test_playbook = '''
# TODO: Create this as test_templates.yml
---
- name: Test Template Rendering
  hosts: all
  gather_facts: yes
  
  tasks:
    - name: Create configs directory
      file:
        path: "./configs"
        state: directory
      delegate_to: localhost
      run_once: true
      
    - name: Generate base configuration from template
      template:
        src: base_config.j2
        dest: "./configs/{{ inventory_hostname }}_base.cfg"
      delegate_to: localhost
      
    - name: Show generated config content
      debug:
        msg: "{{ lookup('file', './configs/' + inventory_hostname + '_base.cfg') }}"

- name: Generate VLAN configs for switches only
  hosts: switches
  gather_facts: no
  
  tasks:
    - name: Generate VLAN configuration
      template:
        src: vlan_config.j2  
        dest: "./configs/{{ inventory_hostname }}_vlans.cfg"
      delegate_to: localhost
'''

print("Create the templates and test playbook using the examples above!")
print("Test with: ansible-playbook -i inventory/hosts.yml test_templates.yml")