# Sample Network Configuration Data
# This file contains sample configuration data that can be used in Ansible playbooks
# Students can modify and extend this data for their exercises

# Campus Network Information
campus:
  name: "Florida State College at Jacksonville"
  domain: "lab.fscj.edu"
  location: "Jacksonville, FL"
  contact: "Network Operations <netops@fscj.edu>"

# Network Infrastructure
infrastructure:
  core_switches:
    - hostname: "CORE-SW01"
      management_ip: "192.168.99.10"
      model: "Catalyst 6500"
      
    - hostname: "CORE-SW02"  
      management_ip: "192.168.99.11"
      model: "Catalyst 6500"
      
  distribution_switches:
    - hostname: "DIST-SW01"
      management_ip: "192.168.99.20"
      model: "Catalyst 3850"
      
    - hostname: "DIST-SW02"
      management_ip: "192.168.99.21"
      model: "Catalyst 3850"
      
  access_switches:
    - hostname: "ACC-SW01"
      management_ip: "192.168.99.30"
      model: "Catalyst 2960"
      location: "Room A101"
      
    - hostname: "ACC-SW02"
      management_ip: "192.168.99.31"
      model: "Catalyst 2960"
      location: "Room B201"

# DHCP Scope Information
dhcp_scopes:
  student_lab_a:
    network: "192.168.10.0"
    mask: "255.255.255.0"
    gateway: "192.168.10.1"
    dns_primary: "8.8.8.8"
    dns_secondary: "8.8.4.4"
    lease_time: "7 days"
    excluded_range: 
      start: "192.168.10.1"
      end: "192.168.10.50"
      
  student_lab_b:
    network: "192.168.11.0"
    mask: "255.255.255.0"
    gateway: "192.168.11.1"
    dns_primary: "8.8.8.8"
    dns_secondary: "8.8.4.4"
    lease_time: "7 days"
    excluded_range:
      start: "192.168.11.1" 
      end: "192.168.11.50"
      
  faculty_network:
    network: "192.168.20.0"
    mask: "255.255.255.0"
    gateway: "192.168.20.1"
    dns_primary: "192.168.30.10"
    dns_secondary: "8.8.8.8"
    lease_time: "30 days"
    excluded_range:
      start: "192.168.20.1"
      end: "192.168.20.100"

# Access Control Policies
access_control:
  student_policies:
    - name: "STUDENT_INTERNET_ACCESS"
      source: "192.168.10.0 0.0.0.255"
      destination: "any"
      protocols: ["tcp/80", "tcp/443", "udp/53"]
      action: "permit"
      
    - name: "BLOCK_STUDENT_TO_FACULTY"
      source: "192.168.10.0 0.0.0.255"
      destination: "192.168.20.0 0.0.0.255"
      protocols: ["ip"]
      action: "deny"
      
  faculty_policies:
    - name: "FACULTY_FULL_ACCESS"
      source: "192.168.20.0 0.0.0.255"
      destination: "any"
      protocols: ["ip"]
      action: "permit"

# QoS Configuration
qos_configuration:
  classes:
    voice:
      dscp_marking: "ef"
      bandwidth_percent: 30
      priority_queue: true
      
    video:
      dscp_marking: "af41"
      bandwidth_percent: 25
      priority_queue: false
      
    data:
      dscp_marking: "default"
      bandwidth_percent: 45
      priority_queue: false

# Monitoring and Management
monitoring:
  snmp:
    communities:
      - name: "public"
        access: "ro"
        
      - name: "fscjnet"
        access: "rw"
        
    trap_destinations:
      - "192.168.99.100"
      - "192.168.99.101"
      
  syslog:
    servers:
      - ip: "192.168.99.100"
        facility: "local7"
        severity: "informational"
        
      - ip: "192.168.99.101"
        facility: "local6"
        severity: "warnings"

# Security Settings
security:
  password_policies:
    minimum_length: 8
    complexity_required: true
    history_count: 5
    max_age_days: 90
    
  login_security:
    max_attempts: 3
    lockout_duration: 300
    banner_required: true
    
  ssh_settings:
    version: 2
    timeout: 600
    authentication_retries: 3
    key_size: 2048

# Backup and Maintenance
maintenance:
  backup:
    schedule: "daily"
    retention_days: 30
    destination: "tftp://192.168.99.100/backups/"
    
  updates:
    maintenance_window: "Sunday 02:00-06:00"
    notification_list: ["netops@fscj.edu"]
    
  monitoring:
    uptime_threshold: 99.5
    response_time_threshold: 100
    bandwidth_threshold: 80