# Exercise 1: Basic Ansible Connection Test
# This playbook demonstrates basic connectivity to Cisco devices
# Learning Objectives:
# - Understand playbook structure
# - Test device connectivity  
# - Gather basic device facts

---
- name: Exercise 1 - Basic Connection Test
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Test connectivity to devices
      cisco.ios.ios_ping:
        dest: 8.8.8.8
        count: 3
      register: ping_result
      
    - name: Display ping results
      debug:
        msg: "Ping to 8.8.8.8 from {{ inventory_hostname }}: {{ ping_result.packet_loss }}% packet loss"
        
    - name: Gather device facts
      cisco.ios.ios_facts:
        gather_subset: 
          - default
          - hardware
      register: device_facts
      
    - name: Display basic device information
      debug:
        msg: |
          Device: {{ inventory_hostname }}
          Model: {{ ansible_net_model }}  
          Version: {{ ansible_net_version }}
          Serial: {{ ansible_net_serialnum }}
          Uptime: {{ ansible_net_uptime }}
          
    - name: Test device reachability with simple command
      cisco.ios.ios_command:
        commands:
          - show clock
          - show users
      register: basic_commands
      
    - name: Display command outputs
      debug:
        var: basic_commands.stdout_lines

# Instructions for Students:
# 1. Update inventory/hosts.yml with your device IP addresses and credentials
# 2. Run: ansible-playbook playbooks/01_basic_connection.yml
# 3. Verify all devices respond successfully
# 4. Review the output to understand device information
# 
# Troubleshooting Tips:
# - Check IP addresses in inventory file
# - Verify credentials (username/password)
# - Ensure SSH is enabled on devices
# - Check firewall/security group settings